name: release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main*
    types: [closed]

jobs:
  release:
    uses: datavisyn/github-workflows/.github/workflows/release-product.yml@new_deployment
    secrets: inherit